var tree = [["WebSyndication","WebSyndication.html","",
                [["Abstracts","WebSyndication\/Abstracts.html","",
                [["ItemInterface","WebSyndication\/Abstracts\/ItemInterface.html","",
                [        ]],["ItemsContainerInterface","WebSyndication\/Abstracts\/ItemsContainerInterface.html","",
                [        ]],["ParserInterface","WebSyndication\/Abstracts\/ParserInterface.html","",
                [        ]],["ReaderInterface","WebSyndication\/Abstracts\/ReaderInterface.html","",
                [        ]],["SimpleObject","WebSyndication\/Abstracts\/SimpleObject.html","",
                [        ]],["StdClass","WebSyndication\/Abstracts\/StdClass.html","",
                [        ]],["XMLDataObject","WebSyndication\/Abstracts\/XMLDataObject.html"," < XMLObject",
                [        ]],["XMLObject","WebSyndication\/Abstracts\/XMLObject.html"," < SimpleObject",
                [        ]],["XMLObjectsCollection","WebSyndication\/Abstracts\/XMLObjectsCollection.html"," < XMLDataObject",
                [        ]]        ]],["Feed","WebSyndication\/Feed.html"," < XMLDataObject",
                [        ]],["FeedCachable","WebSyndication\/FeedCachable.html"," < Feed",
                [        ]],["FeedsCollection","WebSyndication\/FeedsCollection.html"," < Collection",
                [        ]],["Helper","WebSyndication\/Helper.html","",
                [        ]],["Item","WebSyndication\/Item.html"," < XMLDataObject",
                [        ]],["ItemsCollection","WebSyndication\/ItemsCollection.html"," < Collection",
                [        ]],["Parser","WebSyndication\/Parser.html"," < XMLDataObject",
                [        ]],["Renderer","WebSyndication\/Renderer.html","",
                [        ]]        ]]        ]

